# Generated by Django 3.0.3 on 2020-02-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200204_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('NR', 'No Result'), ('W', 'Won'), ('D', 'Draw')], default='NR', max_length=3),
        ),
    ]
