# Generated by Django 3.0.3 on 2020-02-04 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200204_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='next_move_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='player', to='core.Game'),
            preserve_default=False,
        ),
    ]
