# Generated by Django 3.0.3 on 2020-02-04 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200204_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='next_move_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='move_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
