# Generated by Django 3.0.3 on 2020-02-04 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200204_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='moves_to_win_p1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='moves_to_win_p2',
        ),
    ]
